void close(void) {}
void _exit(void) {}
void exit(void) {}
void fork(void) {}
void gettimeofday(void) {}
void kill(void) {}
void memcpy(void) {}
void memmove(void) {}
void memset(void) {}
void open(void) {}
void pipe(void) {}
void printf(void) {}
void puts(void) {}
void rand(void) {}
void read(void) {}
void select(void) {}
void sprintf(void) {}
void srand(void) {}
void strcmp(void) {}
void strlen(void) {}
void strncpy(void) {}
void strstr(void) {}
void time(void) {}
void tolower(void) {}
void waitpid(void) {}
void write(void) {}
