void XAllocColor(void) {}
void XCloseDisplay(void) {}
void XCopyArea(void) {}
void XCreateGC(void) {}
void XCreatePixmap(void) {}
void XCreateSimpleWindow(void) {}
void XDestroyWindow(void) {}
void XDisplayName(void) {}
void XDrawLine(void) {}
void XDrawRectangle(void) {}
void XDrawString(void) {}
void XFillArc(void) {}
void XFillRectangle(void) {}
void XFlush(void) {}
void XFreeFont(void) {}
void XFreeGC(void) {}
void XFreePixmap(void) {}
void XInternAtom(void) {}
void XLoadQueryFont(void) {}
void XLookupKeysym(void) {}
void XMapWindow(void) {}
void XNextEvent(void) {}
void XOpenDisplay(void) {}
void XPending(void) {}
void XSelectInput(void) {}
void XSetFont(void) {}
void XSetForeground(void) {}
void XSetIconName(void) {}
void XSetWMNormalHints(void) {}
void XSetWMProtocols(void) {}
void XStoreName(void) {}
void XTextWidth(void) {}
